### ISSUE TITLE
Error pulling image from dockerhub

### ISSUE THREAD

**Issue by alberttwong** [jorgemoralespou/s2i-java#1]
I0802 19:45:52.325601       1 docker.go:351] Image "jorgemoralespou/s2i-java@sha256:bf8843e2cba6788c33bafe2d6bec7caac60815c152c75786e413986346df1c13" not available locally, pulling ...
I0802 19:45:55.897950       1 docker.go:351] Image "jorgemoralespou/s2i-java@sha256:bf8843e2cba6788c33bafe2d6bec7caac60815c152c75786e413986346df1c13" not available locally, pulling ...
F0802 19:45:59.187012 1 builder.go:204] Error: build error: unable to get jorgemoralespou/s2i-java@sha256:bf8843e2cba6788c33bafe2d6bec7caac60815c152c75786e413986346df1c13

**Comment by alberttwong** [comment]
Found the issue to be  https://access.redhat.com/solutions/2391351

**Comment by joymufeng** [comment]
@alberttwong Is there any solution for this issue?

**Comment by alberttwong** [comment]
@joymufeng did you see my comment on aug 3?   It links to the answer.

**Comment by joymufeng** [comment]
@alberttwong I checked the link [https://access.redhat.com/solutions/2391351](https://access.redhat.com/solutions/2391351), then just found the issue description without answer. Finally, Jorge Morales help me [fix the problem](https://groups.google.com/forum/#!topic/openshift/cbaddAO3iHg).
