### ISSUE TITLE
Need a little help

### ISSUE THREAD

**Issue by Mikedu1988** [jorgemoralespou/s2i-java#12]
Hi, Jorge
I'm new to openshift, and I really need some help .
I imported s2i-java to my project, but i wonder how can I pass MAVEN_ARGS_APPEND to the build. when I create an application in openshift, I can only see two options.
![image](https://user-images.githubusercontent.com/24424690/44017767-0fc96644-9f0c-11e8-88d5-3ed673aed185.png)
cloud you help me on this.

**Comment by der-ali** [comment]
you should click on advanced options at the right bottom. Then you will find a section named "Environment Variables" where you can define this variable
