### ISSUE TITLE
BUILDER_ARGS only used for Gradle

### ISSUE THREAD

**Issue by dbalakirev** [jorgemoralespou/s2i-java#3]
Based on the current README I had the understanding, that the BUILDER_ARGS is used for Maven projects as well.

> - Maven
>   BUILDER_ARGS="package -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga"

But in reality, the _assemble_ file uses MAVEN_ARGS, as it is the S2i convention in general anyway (I think):

`MAVEN_ARGS=${MAVEN_ARGS--e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga package}`

Please let me know if it's only my misunderstanding or something to be fixed in the docs.

Thanks!

**Comment by jmtd** [comment]
I had the same interpretation and was surprised to see -Popenshift warnings in logs for some builds after I'd specified BUILDER_ARGS=package. Specifying MAVEN_ARGS instead worked.
