### ISSUE TITLE
Maven Dependencies (.m2) not cached/restored on subsequent builds

### ISSUE THREAD

**Issue by marcoeig** [jorgemoralespou/s2i-java#5]
If I understand correctly. OpenShift invokes the save_artifacts function automatically to cache e.g., dependencies in order to speed up subsequent builds.

It seems as if this is not happening. On every build Maven downloads the dependencies again which results in a slow build process.

Am I missing something?

**Comment by andrewklau** [comment]
You need to enable incremental builds https://docs.openshift.com/container-platform/3.4/dev_guide/builds/build_strategies.html#incremental-builds

**Comment by jorgemoralespou** [comment]
@marcoeig let me know if the answer by @andrewklau don't fix your problem, else, close the issue.

**Comment by marcoeig** [comment]
@andrewklau thank you very much!
@jorgemoralespou works like a charm now!

down from 2-3 minutes to 15 seconds, nice 👍
